## Explicação: 

As maquinas não podem processar dados de textos em formato bruto, sendo necessario um processo para decompor o texto em um formato numerico que a maquina consiga ler facilmente(processamento de linguagem natural).

- bag-of-words: um dos metodos de pre-processamento de texto mais conhecidos é o saco de palavras, ele vetoriza uma frase ou um texto e essa incrustação de palavras é um formas mais simples de representar um texto em numeros
    1. Criar um indice do vocabulario de palavras do texto.
    2. Construir um vetor numerico para o texto que represente a frequencia com que palavra aparece no texto.

- tf-idf: A frequencia dos termos - a frequencia inversa de documentos, é uma estatistica numerica que tenta refletir a importancia de uma palavra para um documento em um coleção ou corpus. 
- TF(frequencia do terno) é uma medida de quantas vezes um termo aparece em um documento. O peso de um termo que ocorre em um documento é diretamente propocional a sua frequencia.
- IDF(inverso da frequencia nos documentos) é a medida da importancia de um termo. A especificidade de um termo pode ser quantifficada por um função inversa do numero de documentos em que ele ocorre.

## Prática:

#### Carregando bibliotecas

In [109]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import numpy as np
from IPython.display import Markdown
from sklearn.datasets import load_digits
from sklearn.feature_extraction.text import CountVectorizer , TfidfTransformer

1. bag-of-words: gerando vocabulario

In [121]:
frases = [
    "John likes",
    "likes to",
    "to watch",
    "watch movies",
    "Mary likes",
    "likes movies",
    "movies too",
]

In [60]:
#vetor para contagem palavras da lista frases
vetorizador = CountVectorizer()
#colocar em saco de palavras
bag = vetorizador.fit_transform(frases)
#visualizar os tokens exclusivos
print(vectorizer.get_feature_names_out())
#indice de cada token
print(vectorizer.vocabulary_)
#codificação
print(bag.toarray())

['john' 'likes' 'mary' 'movies' 'to' 'too' 'watch']
{'john': 0, 'likes': 1, 'to': 4, 'watch': 6, 'movies': 3, 'mary': 2, 'too': 5}
[[1 1 0 0 0 0 0]
 [0 1 0 0 1 0 0]
 [0 0 0 0 1 0 1]
 [0 0 0 1 0 0 1]
 [0 1 1 0 0 0 0]
 [0 1 0 1 0 0 0]
 [0 0 0 1 0 1 0]]


2. tf-idf: na lista frases cada frase vai ser um documento entao teremos 7 docs

In [123]:
#vetor para contagem palavras da lista frases(frequencia do termo)
#vetorizador = CountVectorizer() reutilizado de bags-of-words
#conversao em matriz frequencia palavras
contap = vetorizador.fit_transform(frases)
# quantos docs e quantas palavras?
print("Temos",contap.shape[0],"docs e",contap.shape[1],"palavras unicas")

# IDF importancia das palavras
# calcular os valores de IDF para palavras
tfidft = TfidfTransformer(smooth_idf=True,use_idf=True)
tfidft.fit(contap)
#tfidfp = tfidf.fit_transform(frases)
# visualização do valores idf 
df_idf = pd.DataFrame(tfidft.idf_, index=vetorizador.get_feature_names_out(),columns=["idf_importancia"]) 
# organiza por importancia ordem crescente quanto menor valor IDF menos exclusiva (aparece em quase todos os docs)
df_idf.sort_values(by=['idf_importancia'])


Temos 7 docs e 7 palavras unicas


idf_importancia
likes          1.470004
movies         1.693147
to             1.980829
watch          1.980829
john           2.386294
mary           2.386294
too            2.386294

In [138]:
# Pontuação TFIDF
# contagem em matriz esparsa
matrizv=vetorizador.transform(frases)
# computando a pontuacao do tf-idf (tf*idf)
tf_idf_vetor=tfidft.transform(matrizv)
# visualização dos valores tf-idf 
vtokens = vetorizador.get_feature_names_out() 
#pega o tfidf vetor para o primeiro doc(primeira frase)
primeiro_doc=tf_idf_vetor[0] 
# pontuação em ordem decrescente 
df = pd.DataFrame(first_document_vector.T.todense(), index=vtokens, columns=["tf-idf"]) 
df.sort_values(by=["tf-idf"],ascending=False)

tf-idf
john    0.851417
likes   0.524489
mary    0.000000
movies  0.000000
to      0.000000
too     0.000000
watch   0.000000